AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-url-to-html  
Globals:
  Function:
    Timeout: 3

Resources:
  UrlToHtmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: url-to-html/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      MemorySize: 1536
      Timeout: 60
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Resource: "arn:aws:s3:::pdf-cache-prod/html-files/*"
      Events:
        UrlToHtml:
          Type: Api
          Properties:
            Path: /render-html
            Method: get

Outputs:
  UrlToHtmlApi:
    Description: "API Gateway endpoint URL for Prod stage for url-to-html function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/render-html/"
  UrlToHtmlFunction:
    Description: "url-to-html Lambda Function ARN"
    Value: !GetAtt UrlToHtmlFunction.Arn
  UrlToHtmlFunctionIamRole:
    Description: "Implicit IAM Role created for url-to-html function"
    Value: !GetAtt UrlToHtmlFunctionRole.Arn
